# Local Development
### Health Check
GET http://localhost:8080/health

### Test if Gemini Works
POST http://localhost:8080/api/gemini/chat
Content-Type: application/json

{
    "prompt": "Generate 3 short riddles."
}

### Get contract
GET http://localhost:8080/api/users/6SUmHWN1wEbVNKMfV9uA2wh0rF03/contracts/movUCr0Jm5FExePzc0ZG

### Upgrade contract to premium
PUT http://localhost:8080/api/users/6SUmHWN1wEbVNKMfV9uA2wh0rF03/contracts/movUCr0Jm5FExePzc0ZG/set-premium

### Summarize Contract
POST http://localhost:8080/api/users/6SUmHWN1wEbVNKMfV9uA2wh0rF03/contracts/movUCr0Jm5FExePzc0ZG/summarize
Content-Type: application/json

### Review Contract
POST http://localhost:8080/api/users/6SUmHWN1wEbVNKMfV9uA2wh0rF03/contracts/OcwAFZQTUrt9oH1OGcsm/review
Content-Type: application/json

### Compare Contract
GET http://localhost:8080/api/users/6SUmHWN1wEbVNKMfV9uA2wh0rF03/contracts/compare?contractId1=OcwAFZQTUrt9oH1OGcsm&contractId2=movUCr0Jm5FExePzc0ZG
Content-Type: application/json


# Production Environment
### Health Check
GET https://legalens.onrender.com/health

### Get contract
GET https://legalens.onrender.com/api/users/6SUmHWN1wEbVNKMfV9uA2wh0rF03/contracts/movUCr0Jm5FExePzc0ZG

### Test if Gemini Works
POST https://legalens.onrender.com/api/gemini/chat
Content-Type: application/json

{
    "prompt": "Generate 3 short riddles."
}

### Summarize Contract
POST https://legalens.onrender.com/api/users/6SUmHWN1wEbVNKMfV9uA2wh0rF03/contracts/movUCr0Jm5FExePzc0ZG/summarize
Content-Type: application/json 