# Local Development
### Health Check
GET http://localhost:8080/health

### Test if Gemini Works
POST http://localhost:8080/api/gemini/chat
Content-Type: application/json

{
    "prompt": "Generate 3 short riddles."
}

### Get contract
GET http://localhost:8080/api/users/ri9dBBETxnc7rtvav1faXE1NaoB3/contracts/og3cp9FPfdivuNFxlD4Q

### Upgrade contract to premium
PUT http://localhost:8080/api/users/ri9dBBETxnc7rtvav1faXE1NaoB3/contracts/og3cp9FPfdivuNFxlD4Q/set-premium

### Summarize Contract
POST http://localhost:8080/api/users/ri9dBBETxnc7rtvav1faXE1NaoB3/contracts/og3cp9FPfdivuNFxlD4Q/summarize
Content-Type: application/json



# Production Environment
### Health Check
GET https://legalens.onrender.com/health

### Get contract
GET https://legalens.onrender.com/api/users/ri9dBBETxnc7rtvav1faXE1NaoB3/contracts/og3cp9FPfdivuNFxlD4Q

### Test if Gemini Works
POST https://legalens.onrender.com/api/gemini/chat
Content-Type: application/json

{
    "prompt": "Generate 3 short riddles."
}

### Summarize Contract
POST https://legalens.onrender.com/api/users/ri9dBBETxnc7rtvav1faXE1NaoB3/contracts/og3cp9FPfdivuNFxlD4Q/summarize
Content-Type: application/json 