name: Java Spring Boot CI/CD Pipeline with Render

on:
  push:
    # Only run this workflow when pushing to the "CI/CD Pipeline" branch
    branches: 
      - 'CI/CD-Pipeline'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up JDK (update version if desired)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build the Spring Boot project with Maven (in subdirectory if needed)
      - name: Build with Maven
        working-directory: ./LegaLensBackend
        run: mvn clean install

      # 4. Run tests (also in subdirectory)
      - name: Run tests
        working-directory: ./LegaLensBackend
        run: mvn test

      # 5. Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }} \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'