name: Java Spring Boot CI/CD Pipeline with Render
 
 on:
   push:
     branches: 
       - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
       # 1. Decode and Create adc-key.json
      - name: Decode adc-key.json
      run: |
        echo "${{ secrets.VERTEX_API_KEY }}" | base64 -d > LegaLensBackend/src/main/resources/adc-key.json

       # 2. Deploy to Render
       - name: Deploy to Render
         run: |
           curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }} \
             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
             -H "Content-Type: application/json" \
             -d '{}'