name: React Vite CI/CD with Vercel

on:
  push:
    branches:
      - CI/CD-Pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Set up environment variables
      - name: Set up environment variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV

      # Step 4: Decode and create .env file
      - name: Decode and Create .env File
        run: echo "${{ secrets.FIREBASE_ENV }}" | base64 -d > .env

      # Step 5: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./Frontend

      # Step 6: Build the Vite React app
      - name: Build the app
        run: npm run build
        working-directory: ./Frontend

      # Step 7: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 8: Deploy to Vercel with Explicit Org & Project ID
      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=production --token "${{ secrets.VERCEL_TOKEN }}" --org-id="${{ secrets.VERCEL_ORG_ID }}" --project-id="${{ secrets.VERCEL_PROJECT_ID }}"
          vercel build --prod --token "${{ secrets.VERCEL_TOKEN }}" --org-id="${{ secrets.VERCEL_ORG_ID }}" --project-id="${{ secrets.VERCEL_PROJECT_ID }}"
          vercel deploy --prod --token "${{ secrets.VERCEL_TOKEN }}" --org-id="${{ secrets.VERCEL_ORG_ID }}" --project-id="${{ secrets.VERCEL_PROJECT_ID }}"
        working-directory: Frontend